project:
  type: website
  output-dir: docs

website:
  title: "GLMs dont suck"
  navbar:
    left:
      - href: GLMsAreGood.qmd
        text: Presentation

format:
  html:
    theme: cosmo
    css: styles.css
    code-fold: true